# Generated by Django 5.2 on 2025-04-20 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscourseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Unique identifier for the user in Discourse', max_length=255, null=True, unique=True)),
                ('username', models.CharField(blank=True, help_text='Discourse username', max_length=150, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address linked to the Discourse account', max_length=254, null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync with Discourse', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record update timestamp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discourse_profile', to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Discourse Profile',
                'verbose_name_plural': 'Discourse Profiles',
            },
        ),
        migrations.CreateModel(
            name='SsoEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('sync', 'Sync'), ('error', 'Error')], help_text='Type of SSO event', max_length=20)),
                ('payload_details', models.TextField(blank=True, help_text='SSO payload details (encoded or decoded) for debugging purposes')),
                ('signature', models.CharField(blank=True, help_text='The HMAC signature of the SSO payload', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was recorded')),
                ('user', models.ForeignKey(blank=True, help_text='Associated Django user (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Event Log',
                'verbose_name_plural': 'SSO Event Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
